source: .

collections_config:
  projects_es:
    path: src/content/projects/es
    name: Projects (ES)
    icon: rocket_launch
    _enabled_editors:
      - content
    schemas:
      default:
        path: schemas/project.md
  projects_en:
    path: src/content/projects/en
    name: Projects (EN)
    icon: rocket_launch
    _enabled_editors:
      - content
    schemas:
      default:
        path: schemas/project.md
  site_es:
    path: src/content/site/es.yml
    name: Site (ES)
    icon: settings
    _enabled_editors:
      - data
  site_en:
    path: src/content/site/en.yml
    name: Site (EN)
    icon: settings
    _enabled_editors:
      - data
  skills:
    path: src/content/skills/skills.yml
    name: Skills
    icon: psychology
    _enabled_editors:
      - data

paths:
  uploads: public/uploads
  static: public

timezone: Europe/Madrid

markdown:
  engine: commonmark
